[build]
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "18"
  NEXT_DISABLE_TYPE_CHECK = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
